const hardwareDescriptionZhMap: Record<string, string> = {
  'Absolute top-end 4K and AI acceleration GPU.': '顶级 4K 与 AI 加速旗舰显卡。',
  'Balanced 1440p option with good memory capacity.': '均衡的 1440p 方案，显存容量充足。',
  'Balanced gaming and creator throughput for mid-high builds.': '面向中高端整机的游戏与创作性能平衡。',
  'Budget kit for very tight build targets.': '面向极限预算装机的内存套装。',
  'Budget PCIe 4.0 upgrade for daily usage.': '适合日常使用的高性价比 PCIe 4.0 升级盘。',
  'Clean aesthetic mid-tower with direct GPU airflow.': '外观简洁的中塔机箱，具备直通显卡风道。',
  'Entry DDR5 board for price-sensitive Intel builds.': '面向价格敏感 Intel 装机的入门 DDR5 主板。',
  'Entry gaming CPU for strict budgets.': '严格预算下的入门游戏 CPU。',
  'Entry-level 1080p card with good pricing in sales.': '入门级 1080p 显卡，促销时价格友好。',
  'Excellent 1440p high-refresh card with DLSS 3.': '适合 1440p 高刷的优秀显卡，支持 DLSS 3。',
  'Extreme compute CPU for workstation-heavy users.': '面向重度工作站用户的极致算力 CPU。',
  'Feature-rich mid-range board for heavy IO users.': '功能丰富的中端主板，适合高 I/O 需求用户。',
  'Great headroom for high-end GPU builds.': '为高端显卡装机提供充足功率余量。',
  'Great value rasterization card for 1440p and modded workloads.': '在 1440p 与重纹理/模组负载下有出色光栅性价比。',
  'High airflow case with easy cable routing.': '高风量机箱，走线友好。',
  'High-end mixed workload CPU with strong burst clocks.': '适合混合负载的高端 CPU，瞬时频率表现强。',
  'High-end SSD with robust random IO performance.': '高端 SSD，随机 I/O 性能强劲。',
  'High-frequency option for tuned systems.': '面向调校型平台的高频内存选项。',
  'Looks attractive but restricts airflow severely.': '外观讨喜，但风道受限较明显。',
  'Low-cost SSD option for non-critical storage.': '适合非关键数据的低成本 SSD 选项。',
  'Mainstream Intel board with practical feature set.': '主流 Intel 主板，功能配置实用。',
  'Power-efficient entry 1080p card with modern encoders.': '低功耗入门 1080p 显卡，配备新一代编码器。',
  'Practical budget PSU for entry and mid-range systems.': '适合入门与中端平台的实用型预算电源。',
  'Reliable AM5 board with balanced IO and VRM quality.': '稳定可靠的 AM5 主板，I/O 与供电表现均衡。',
  'Reliable premium PSU with excellent transient response.': '稳定可靠的高端电源，瞬态响应优秀。',
  'Stable DDR5 pair for mainstream users.': '面向主流用户的稳定 DDR5 套条。',
  'Strong mainstream gaming CPU with low power draw.': '主流游戏性能强，功耗控制出色。',
  'Sweet-spot DDR5 kit for gaming and creator workloads.': '兼顾游戏与创作负载的甜点位 DDR5 套装。',
  'Top-tier gaming frame consistency with 3D cache.': '依托 3D 缓存带来顶级游戏帧稳定性。',
  'Top-tier PCIe 4.0 SSD for gaming and production.': '面向游戏与生产力的顶级 PCIe 4.0 SSD。',
  'Unverified budget PSU with unclear protections.': '未经充分验证的低价电源，保护机制不明确。',
  'Value chassis with strong out-of-box airflow.': '高性价比机箱，开箱即有较强风量。',
};

const hardwareHighlightZhMap: Record<string, string> = {
  'Aesthetic look': '外观好看',
  Affordable: '价格亲民',
  'Affordable 1080p build fit': '适合低预算 1080p 装机',
  'Affordable DDR5 entry': '低成本 DDR5 入门',
  'ATX 3.0 ready': '支持 ATX 3.0',
  'Best AM5 entry point': 'AM5 入门优选',
  'Build-friendly interior': '内部空间装机友好',
  'Compact footprint': '占地紧凑',
  'Competitive price-to-performance': '性价比有竞争力',
  'Easy cooling': '散热压力小',
  'Efficient for class': '同级能效优秀',
  'Excellent latency/value': '时序与价格表现优秀',
  'Excellent single-core output': '单核性能优秀',
  'Excellent sustained throughput': '持续吞吐表现优秀',
  'Excellent thermal design': '散热设计优秀',
  'Excellent value score': '价值评分优秀',
  'Good cable management': '走线体验好',
  'Good IO layout': 'I/O 布局合理',
  'Good sale pricing': '促销价格友好',
  'Good stability': '稳定性良好',
  'Great all-round speed': '全能速度表现优秀',
  'Great AM5 value': 'AM5 平台性价比高',
  'Great value': '高性价比',
  'High overclock headroom': '超频空间大',
  'Large VRAM for price': '同价位显存容量大',
  'Leading game FPS': '游戏帧率领先',
  'Long warranty': '质保期长',
  'Low entry cost': '入门成本低',
  'Low price': '价格低',
  'Low ripple': '纹波低',
  'Many included fans': '附带风扇数量多',
  'Mature platform': '平台成熟',
  'PCIe 5.0 support': '支持 PCIe 5.0',
  'Power-efficient high-end': '高端且能效出色',
  'Robust VRM': '供电模组扎实',
  'Simple plug-and-play': '即插即用简单',
  'Solid DLSS support': 'DLSS 支持完善',
  'Stable memory support': '内存兼容稳定',
  'Strong all-around profile': '综合表现强',
  'Strong BIOS support': 'BIOS 支持完善',
  'Strong multi-core': '多核性能强',
  'Strong ray tracing': '光追性能强',
  'Top productivity': '生产力性能顶级',
  'Unmatched raw performance': '原始性能无可匹敌',
  'Very cheap': '非常便宜',
  'Very low cost': '成本极低',
  'Very low power use': '功耗很低',
  'Wide platform compatibility': '平台兼容范围广',
  'Widely available': '供货广泛',
};

const hardwareWarningZhMap: Record<string, string> = {
  '16GB can be limiting in modern workloads': '16GB 在现代负载下可能偏紧',
  '8GB VRAM limits future AAA texture settings': '8GB 显存在未来 3A 纹理设置下受限',
  'Controller consistency can vary by batch': '主控一致性可能因批次存在差异',
  'Extreme price and power demand': '价格与功耗需求都非常高',
  'High motherboard power requirements': '对主板供电要求较高',
  'High noise under load': '高负载下噪音较高',
  'Higher peak power under full load': '满载峰值功耗较高',
  'Limited expansion for future upgrades': '后续升级扩展空间有限',
  'Limited RT performance': '光追性能有限',
  'Limited upgrade longevity': '升级生命周期有限',
  'Lower sustained write than premium drives': '持续写入低于高端盘',
  'Needs robust cooling': '需要更强散热',
  'Not ideal for future high-end GPUs': '不适合未来高端显卡升级',
  'Overkill for pure gaming rigs': '对纯游戏装机而言偏过剩',
  'Poor thermals': '散热表现较差',
  'Potential safety risk': '存在潜在安全风险',
  'Premium pricing for small real-world gain': '实际收益有限但定价偏高',
  'Ray tracing behind NVIDIA peers': '光追表现落后于同级 NVIDIA',
  'Slightly high for strict budget builds': '对极限预算装机略贵',
  'Unstable output under load': '负载下输出不稳定',
};

export function localizeHardwareDescription(description: string): string {
  return hardwareDescriptionZhMap[description] ?? description;
}

export function localizeHardwareHighlight(highlight: string): string {
  return hardwareHighlightZhMap[highlight] ?? highlight;
}

export function localizeHardwareWarning(warning: string): string {
  return hardwareWarningZhMap[warning] ?? warning;
}
